development:
  sessions:
    default:
      database: ride_journal_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: ride_journal_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
